### ISSUE TITLE
Error in OAuth2Ex.HTTP.decode_body

### ISSUE THREAD

**Issue by optikfluffel** [parroty/oauth2ex#10]
Hi, I'm using oauth2ex with the SoundCloud API. When I get a unauthorised answer with headers that look like this:

```elixir
[
  {"Access-Control-Allow-Headers", "Accept, Authorization, Content-Type, Origin"}, 
  {"Access-Control-Allow-Methods", "GET, PUT, POST, DELETE"},
  {"Access-Control-Allow-Origin", "*"}, 
  {"Access-Control-Expose-Headers", "Date"},
  {"Cache-Control", "no-cache"},
  {"Content-Type", "application/json; charset=utf-8"},
  {"Date", "Sat, 25 Jul 2015 07:19:48 GMT"},
  {"Server", "am/2"},
  {"Status", "401 Unauthorized"},
  {"Content-Length", "51"}
]
```

I get an exception:
```
** (exit) an exception was raised:
    ** (ArgumentError) the access protocol for lists expect the key to be an atom, got: "Content-Type"
        (elixir) lib/access.ex:56: Access.List.get/2
        (oauth2ex) lib/oauth2ex/http.ex:72: OAuth2Ex.HTTP.decode_body/1
        (oauth2ex) lib/oauth2ex/http.ex:59: OAuth2Ex.HTTP.request/6
```

Am I doing something wrong?

**Comment by parroty** [comment]
Thanks for the report. I haven't been able to find specific issue with the posted header.

Can you post your mix.exs and mix.lock file? I couldn't find the direct assiation with master code and the error message. Also would like to check the HTTPoison version.
